services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodscan_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db


  web:
    image: nginx:alpine
    container_name: foodscan_web
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: foodscan_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodscan
      MYSQL_USER: foodscan_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  default:
    name: foodscan_network
